pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    environment {
        // Исправлено: добавлены двойные слэши для экранирования пути в Windows
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        DOCKERHUB_CREDENTIALS_ID = 'Andrei_Docker_Id'
        DOCKERHUB_REPO = 'andrei1033/TemperatureConverter'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage ('check'){
            steps{
                git 'https://github.com/Andrei1033/Suunnittelumallit_TX00EY29-3012'
            }
        }

        stage ('build'){
            steps{
                // Переходим в подпапку, где лежит pom.xml
                dir('OTP1_inclass1_assignment_AndreiTsizikov') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('test') {
            steps{
                // Также выполняем тесты из папки с проектом
                dir('OTP1_inclass1_assignment_AndreiTsizikov') {
                    bat 'mvn test'
                }
            }
        }

        stage('jacoco'){
            steps{
                jacoco()
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Если Dockerfile лежит в корне репозитория, оставьте без dir.
                    // Если Dockerfile лежит внутри папки проекта, используйте dir, как указано ниже:
                    dir('OTP1_inclass1_assignment_AndreiTsizikov') {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }
    }
}
