pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        DOCKERHUB_CREDENTIALS_ID = 'Andrei_Docker_Id'
        DOCKERHUB_REPO = 'andrei1033/temperature_converter'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Andrei1033/Suunnittelumallit_TX00EY29-3012'
            }
        }

        stage('Build') {
            steps {
                dir('OTP1_inclass1_assignment_AndreiTsizikov') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('OTP1_inclass1_assignment_AndreiTsizikov') {
                    bat 'mvn test'
                }
            }
        }

        stage('JaCoCo Report') {
            steps {
                dir('OTP1_inclass1_assignment_AndreiTsizikov') {
                    jacoco()
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('OTP1_inclass1_assignment_AndreiTsizikov') {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }
    }
}